######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 31 19:08:24 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += pointer.cpp

include(/usr/src/cpp/common.pri)

