######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 21 13:48:38 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += thing.h
SOURCES += thing-demo.cpp thing.cpp
