######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 21 20:10:53 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += thing.h
SOURCES += thing-demo.cpp thing.cpp

include(/usr/src/cpp/common.pri)

