######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 24 00:27:41 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += fraction.h
SOURCES += fraction-demo.cpp fraction.cpp

include(/usr/src/cpp/common.pri)

