######################################################################
# Automatically generated by qmake (2.01a) Mon Sep 8 05:18:38 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += ex8-4.cpp ex8-6.cpp ex8-7.cpp ex8-8.cpp

include(/usr/src/cpp/common.pri)

