######################################################################
# Automatically generated by qmake (2.01a) Sun Feb 9 11:52:50 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += ex1-29.cpp

include(/usr/src/cpp/common.pri)

