######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 13 05:16:14 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += ex1.12.cpp
