######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 10 19:43:08 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += complex.h
SOURCES += complex.cpp

include(/usr/src/cpp/common.pri)

