######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 10 05:29:52 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += fraction.h
SOURCES += fraction-client.cpp fractionz.cpp

include(/usr/src/cpp/common.pri)

