######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 24 18:53:14 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += fac.cpp

include (/usr/src/cpp/common.pri)
