######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 21 13:37:56 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += compute.cpp

include(/usr/src/cpp/common.pri)

