######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 12 16:37:42 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += ex1-30.cpp

include(/usr/src/cpp/common.pri)

