######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 20 04:35:45 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qdemo.cpp

include(/usr/src/cpp/common.pri)

