######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 4 22:43:59 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qtex1.cpp

include(/usr/src/cpp/common.pri)
