######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 18 18:37:11 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += ex1.cpp

include(/usr/src/cpp/common.pri)
