######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 20 02:00:06 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += test.cpp
