######################################################################
# Automatically generated by qmake (2.01a) Sun Feb 9 13:41:28 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += ex1-28.cpp

include(/usr/src/cpp/common.pri)

