######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 24 21:28:07 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += ex1.8.cpp
